Repository hapijs/hoek, pull requests merged in 2018-11, with the labels that each got.

#242 Rework deepEqual()
  lib/deep-equal.js
  lib/index.js
  test/index.js
Labels: bug, enhancement

#276 Fix contain() with duplicates and only
  lib/index.js
  test/index.js
Labels: bug

#279 Add changelog.md
  CHANGELOG.md
Labels: documentation

#281 Symbol support
  API.md
  lib/deep-equal.js
  lib/index.js
  test/index.js
Labels: enhancement
