Repository hapijs/hoek, pull requests merged in 2019-05, with the labels that each got.

#294 Handle promises in deepEqual()
  lib/deep-equal.js
  test/index.js
Labels: bug

#297 Clone Map and Set
  lib/index.js
  test/index.js
Labels: enhancement

#298 Typescript enhancements
  lib/index.d.ts
Labels: types

#301 Fix: Add map and set to seen map
  lib/index.js
  test/index.js
Labels: bug

#302 Fix clone of subclassed Set and Map
  lib/deep-equal.js
  lib/index.js
  lib/types.js
  test/index.js
Labels: bug
