Repository hapijs/hoek, pull requests merged in 2022-12, with the labels that each got.

#382 Refactor AssertError
  lib/assert.js
  lib/error.js
  lib/errors.js
  lib/index.d.ts
  lib/index.js
  test/esm.js
  test/index.js
  test/index.ts
Labels: feature, breaking changes, types

#380 Explicitly export modules
  lib/assert.js
  lib/assertError.js
  lib/index.js
  lib/index.mjs
  package.json
  test/esm.js
  test/exports.js
Labels: feature, breaking changes

#384 chore: add individual module types
  lib/applyToDefaults.d.ts
  lib/assert.d.ts
  lib/assertError.d.ts
  lib/bench.d.ts
  lib/block.d.ts
  lib/clone.d.ts
  lib/contain.d.ts
  lib/deepEqual.d.ts
  lib/escapeHeaderAttribute.d.ts
  lib/escapeHtml.d.ts
  lib/escapeJson.d.ts
  lib/escapeRegex.d.ts
  lib/flatten.d.ts
  lib/ignore.d.ts
  lib/intersect.d.ts
  lib/isPromise.d.ts
  lib/merge.d.ts
  lib/once.d.ts
  lib/reach.d.ts
  lib/reachTemplate.d.ts
  lib/stringify.d.ts
  lib/wait.d.ts
  test/index.ts
Labels: types
